enviromage.settings:
  type: config_object
  label: Environment Configuration List Content Type Settings
  mapping:
    settings:
      type: sequence
      label: Configurations to retrieve
      sequence:
        type: string
        label: Content type
    modules_list:
      type: sequence
      label: Modules To Get Size
      sequence:
        type: string
        label: Content type
    composer_package:
      type: sequence
      label: Package To Be Updated
      sequence:
        type: string
        label: Content type
    composer_command:
      type: string
      label: Composer Command To Be Run
