enviromage.settings:
  type: config_object
  label: Environment Configuration List Content Type Settings
  mapping:
    settings:
      type: sequence
      label: Configurations to retrieve
      sequence:
        type: string
        label: Content type
